import Link from 'next/link';

export const metadata = {
  title: "Next.js Demo App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
        <div className="w-full max-w-[1000px] flex flex-col items-center pt-6 pb-6 px-4">
          
          <h1 className="bg-slate-200">Hello World!</h1>

          <main className="w-full mt-10">{children}</main>
        </div>
  );
}
